//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudenRegister.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsRegister
    {
        public int id { get; set; }
        public Nullable<int> Rol_Number { get; set; }
        public string Names { get; set; }
        public Nullable<int> Age { get; set; }
        public string Course { get; set; }
    }
}
