//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParfumApi.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parfum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parfum()
        {
            this.CategoryParfums = new HashSet<CategoryParfum>();
            this.Saleprices = new HashSet<Saleprice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> BrendID { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<bool> New { get; set; }
        public Nullable<int> DensityId { get; set; }
    
        public virtual Brend Brend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryParfum> CategoryParfums { get; set; }
        public virtual Density Density { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saleprice> Saleprices { get; set; }
    }
}
