//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParfumApi.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saleprice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saleprice()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SizeMlId { get; set; }
        public Nullable<int> ParfumID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Parfum Parfum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual SizeMl SizeMl { get; set; }
    }
}
