//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParfumApi.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePriceUI
    {
        public int Id { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> ParfumId { get; set; }
    }
}
