//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.SalestoBooks = new HashSet<SalestoBook>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> TypesId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Buybook { get; set; }
        public Nullable<System.DateTime> SendBook { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Login_Users Login_Users { get; set; }
        public virtual Typess Typess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalestoBook> SalestoBooks { get; set; }
    }
}
